//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdditionalParameter
    {
        public int TableID { get; set; }
        public string No_ { get; set; }
        public string ParameterNo_ { get; set; }
        public string ParameterValueText { get; set; }
        public decimal ParameterValueDec_ { get; set; }
        public string ParameterDescription { get; set; }
        public Nullable<int> SequenceNo_ { get; set; }
        public string RelatedParameterNo_ { get; set; }
        public string RelatedParameterValueText { get; set; }
        public Nullable<decimal> RelatedParameterValueDec_ { get; set; }
        public string RelatedParameterDescription { get; set; }
    }
}
