//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankAccount
    {
        public string No_ { get; set; }
        public Nullable<int> AccountType { get; set; }
        public Nullable<int> Type { get; set; }
        public string Name { get; set; }
        public string BankCode { get; set; }
        public string BankAccountNo_ { get; set; }
        public string IBAN { get; set; }
        public string SWIFTCode { get; set; }
        public string BankBic { get; set; }
        public string CurrencyCode { get; set; }
        public Nullable<byte> Blocked { get; set; }
        public string ResponsibiltyCenter { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<decimal> Balance_LCY_ { get; set; }
        public Nullable<System.Guid> ModifiedUserID { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
