//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaignBasket
    {
        public string CampBasket_No { get; set; }
        public string CampBasket_ResponsibilityCenter { get; set; }
        public string CampBasket_Description { get; set; }
        public Nullable<System.DateTime> CampBasket_StartingDate { get; set; }
        public Nullable<System.DateTime> CampBasket_EndingDate { get; set; }
        public Nullable<int> CampBasket_Type { get; set; }
        public Nullable<int> CampBasket_DiscountType { get; set; }
        public Nullable<decimal> CampBasket_Quantity { get; set; }
        public Nullable<decimal> CampBasket_Amount { get; set; }
        public Nullable<decimal> CampBasket_Sequence { get; set; }
        public Nullable<decimal> CampBasket_DiscountValue { get; set; }
    }
}
