//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeletedSalesHeader
    {
        public string No_ { get; set; }
        public int DocumentType { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> PostingDate { get; set; }
        public Nullable<System.DateTime> ShipmentDate { get; set; }
        public string Sell_toCustomerNo { get; set; }
        public string Sell_toCustomerName { get; set; }
        public string Sell_toAddress { get; set; }
        public string Sell_toCity { get; set; }
        public string Sell_toPostCode { get; set; }
        public string Sell_toCountry { get; set; }
        public string Ship_toAddress { get; set; }
        public string Ship_toCity { get; set; }
        public string Ship_toCountry { get; set; }
        public Nullable<int> Status { get; set; }
        public string PaymentTermsCode { get; set; }
        public string PaymentMethodCode { get; set; }
        public string ShipmentMethodCode { get; set; }
        public string CurrencyCode { get; set; }
        public Nullable<decimal> CurrencyFactor { get; set; }
        public string CustomerPriceGroup { get; set; }
        public Nullable<bool> PricesIncludingVat { get; set; }
        public Nullable<int> InvoiceDisc_Type { get; set; }
        public Nullable<decimal> InvoiceDiscoutAmount { get; set; }
        public string SalespersonCode { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> AmountIncludingVat { get; set; }
        public string VATRegistrationNo_ { get; set; }
        public string ExternalDocumentNo_ { get; set; }
        public string ShippingAgentCode { get; set; }
        public string ResponsibilityCenter { get; set; }
        public Nullable<bool> VatInvoice { get; set; }
        public Nullable<bool> Waybill { get; set; }
        public string PlasticCardNo { get; set; }
        public Nullable<decimal> InvoiceDiscountAmount { get; set; }
        public Nullable<bool> IsEmployee { get; set; }
        public string Guid { get; set; }
        public string ModifiedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string PostingDescription { get; set; }
    }
}
