//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class GenJournalLineArchive
    {
        public string TemplateName { get; set; }
        public string BathName { get; set; }
        public int LineNo_ { get; set; }
        public Nullable<System.DateTime> PostingDate { get; set; }
        public Nullable<int> DocumentType { get; set; }
        public Nullable<int> AccountType { get; set; }
        public string AccountNo_ { get; set; }
        public string Description { get; set; }
        public Nullable<int> Bal_AccountType { get; set; }
        public string Bal_AccountNo_ { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string CurrencyCode { get; set; }
        public Nullable<decimal> CurrencyFactor { get; set; }
        public string Salespers__Purch_Code { get; set; }
        public string ResponsibilityCenter { get; set; }
        public string PlasticCardNo { get; set; }
        public string PresentCardNo { get; set; }
        public string PaymentMethodCode { get; set; }
        public string PaymentMethodCodeGeo { get; set; }
        public Nullable<System.Guid> ModifiedUserID { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
