//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemItem
    {
        public string BaseItemNo_ { get; set; }
        public string RelatedItemNo_ { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string BaseUnitOfMeasure { get; set; }
        public string RelatedUnitOfMeasure { get; set; }
    }
}
