//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemPicture
    {
        public string ItemNo_ { get; set; }
        public int PictureNo_ { get; set; }
        public string Description { get; set; }
        public byte[] Content { get; set; }
    }
}
