//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemCustomer
    {
        public string ItemNo_ { get; set; }
        public string CustomerNo_ { get; set; }
        public Nullable<int> Type { get; set; }
        public string CustomerItemNo_ { get; set; }
        public string VariantCode { get; set; }
        public Nullable<bool> Like { get; set; }
        public bool IsNew { get; set; }
    }
}
