//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemCrossReference
    {
        public string ItemNo_ { get; set; }
        public string VariantCode { get; set; }
        public string UnitOfMeasure { get; set; }
        public int Cross_ReferenceType { get; set; }
        public string Cross_ReferenceTypeNo_ { get; set; }
        public string Cross_ReferenceNo_ { get; set; }
        public decimal Qty_PerUnitOfMeasure { get; set; }
        public string Description { get; set; }
        public Nullable<bool> DiscontinueBarCode { get; set; }
    }
}
