//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemLedgerEntry
    {
        public int EntryNo_ { get; set; }
        public Nullable<int> EntryType { get; set; }
        public string ItemNo { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<System.DateTime> PostingDate { get; set; }
        public Nullable<int> DocumentType { get; set; }
        public string DocumentNo_ { get; set; }
        public Nullable<int> DocumentLineNo { get; set; }
        public string LocationCode { get; set; }
        public Nullable<bool> Open { get; set; }
        public Nullable<bool> Positive { get; set; }
        public string VariantCode { get; set; }
        public Nullable<decimal> Qty_PerUnitOfMeasure { get; set; }
        public string UnitOfMeasureCode { get; set; }
        public string ItemCategoryCode { get; set; }
        public string ProductGroupCode { get; set; }
        public string ProductSubGroupCode { get; set; }
        public string SerialNo_ { get; set; }
        public string LotNo_ { get; set; }
        public Nullable<System.Guid> ModifiedUserID { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
