//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemVehicleModel
    {
        public string ItemNo_ { get; set; }
        public string ManufacturerCode { get; set; }
        public string ModelNo_ { get; set; }
        public string CabType { get; set; }
        public string Engine { get; set; }
        public System.DateTime ManufacturingStartDate { get; set; }
        public string OutputPH { get; set; }
        public string ItemDescription { get; set; }
        public string ManufacturerName { get; set; }
        public string ModelDescription { get; set; }
        public Nullable<System.DateTime> ManufacturingEndDate { get; set; }
        public string TecDoc_ID { get; set; }
    }
}
