//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoyaltyCard
    {
        public string No_ { get; set; }
        public Nullable<int> Type { get; set; }
        public string CustomerNo { get; set; }
        public string CustomerName { get; set; }
        public Nullable<System.DateTime> ValidTill { get; set; }
        public Nullable<bool> Blocked { get; set; }
        public string PCPaymentMethodeCode { get; set; }
        public Nullable<decimal> PresentAmount { get; set; }
        public Nullable<bool> PresentCardSold { get; set; }
        public Nullable<bool> PresentCardReceivd { get; set; }
        public Nullable<int> DiscountCalcForm { get; set; }
        public Nullable<int> DiscountCalculation { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public Nullable<System.Guid> ModifiedUserID { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<decimal> PeriodCumulativeAmount { get; set; }
    }
}
