//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class POSWR1Entities : DbContext
    {
        public POSWR1Entities()
            : base("name=POSWR1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActiveSession> ActiveSessions { get; set; }
        public virtual DbSet<AutoNumber> AutoNumbers { get; set; }
        public virtual DbSet<BankAccount> BankAccounts { get; set; }
        public virtual DbSet<CampaignBasket> CampaignBaskets { get; set; }
        public virtual DbSet<DeletedSalesHeader> DeletedSalesHeaders { get; set; }
        public virtual DbSet<DeletedSalesLine> DeletedSalesLines { get; set; }
        public virtual DbSet<GenJournalLineArchive> GenJournalLineArchives { get; set; }
        public virtual DbSet<ItemCatalogue> ItemCatalogues { get; set; }
        public virtual DbSet<ItemLedgerEntry> ItemLedgerEntries { get; set; }
        public virtual DbSet<ItemPicture> ItemPictures { get; set; }
        public virtual DbSet<ItemUnitOfMeasure> ItemUnitOfMeasures { get; set; }
        public virtual DbSet<LoyaltyCard> LoyaltyCards { get; set; }
        public virtual DbSet<Manufacturer> Manufacturers { get; set; }
        public virtual DbSet<PaymentMethod> PaymentMethods { get; set; }
        public virtual DbSet<POSUser> POSUsers { get; set; }
        public virtual DbSet<PosUserType> PosUserTypes { get; set; }
        public virtual DbSet<ProductSubGroup> ProductSubGroups { get; set; }
        public virtual DbSet<ProjectedItemReceipt> ProjectedItemReceipts { get; set; }
        public virtual DbSet<ReleasedSalesLine> ReleasedSalesLines { get; set; }
        public virtual DbSet<ResponsibilityCenter> ResponsibilityCenters { get; set; }
        public virtual DbSet<SalesLine> SalesLines { get; set; }
        public virtual DbSet<Salesperson_Purchaser> Salesperson_Purchaser { get; set; }
        public virtual DbSet<SalesPrice> SalesPrices { get; set; }
        public virtual DbSet<ShippingAgent> ShippingAgents { get; set; }
        public virtual DbSet<UnitOfMeasure> UnitOfMeasures { get; set; }
        public virtual DbSet<ItemCrossReference> ItemCrossReferences { get; set; }
        public virtual DbSet<Ship_to_Address> Ship_to_Address { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<ItemCategory> ItemCategories { get; set; }
        public virtual DbSet<ProductGroup> ProductGroups { get; set; }
        public virtual DbSet<RegionBudgetActual> RegionBudgetActuals { get; set; }
        public virtual DbSet<ItemItem> ItemItems { get; set; }
        public virtual DbSet<PaymentSchedule> PaymentSchedules { get; set; }
        public virtual DbSet<SalesHeader> SalesHeaders { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<PostCodeCity> PostCodeCities { get; set; }
        public virtual DbSet<PostedPaymentSchedule> PostedPaymentSchedules { get; set; }
        public virtual DbSet<ReleasedPaymentSchedule> ReleasedPaymentSchedules { get; set; }
        public virtual DbSet<PostedSalesHeader> PostedSalesHeaders { get; set; }
        public virtual DbSet<ReleasedSalesHeader> ReleasedSalesHeaders { get; set; }
        public virtual DbSet<PostedSalesLine> PostedSalesLines { get; set; }
        public virtual DbSet<PostedGenJournalLine> PostedGenJournalLines { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<ReleasedGenJournalLine> ReleasedGenJournalLines { get; set; }
        public virtual DbSet<Comment_Line> Comment_Line { get; set; }
        public virtual DbSet<ItemVehicleModel> ItemVehicleModels { get; set; }
        public virtual DbSet<AdditionalParameter> AdditionalParameters { get; set; }
        public virtual DbSet<ItemCustomer> ItemCustomers { get; set; }
        public virtual DbSet<ItemSuggestion> ItemSuggestions { get; set; }
        public virtual DbSet<POSMessageEntry> POSMessageEntries { get; set; }
        public virtual DbSet<UserSetup> UserSetups { get; set; }
        public virtual DbSet<ItemVehicleGroup> ItemVehicleGroups { get; set; }
        public virtual DbSet<VehicleGroup> VehicleGroups { get; set; }
        public virtual DbSet<GenJournalLine> GenJournalLines { get; set; }
        public virtual DbSet<VehicleModel> VehicleModels { get; set; }
        public virtual DbSet<Vehicle> Vehicles { get; set; }
        public virtual DbSet<Vendor> Vendors { get; set; }
        public virtual DbSet<Dimension_Value> Dimension_Values { get; set; }
        public virtual DbSet<StockkeepingUnit> StockkeepingUnits { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<ItemsView> ItemsViews { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
        public virtual DbSet<CompanyInformation> CompanyInformations { get; set; }
        public virtual DbSet<SavedItemsForLaterSale> SavedItemsForLaterSales { get; set; }
        public virtual DbSet<ItemLedgerEntryFull> ItemLedgerEntryFulls { get; set; }
    
        public virtual ObjectResult<ItemsViewProcedure_Result> ItemsViewProcedure(string customerCode, string customerGroup, string locationCode)
        {
            var customerCodeParameter = customerCode != null ?
                new ObjectParameter("customerCode", customerCode) :
                new ObjectParameter("customerCode", typeof(string));
    
            var customerGroupParameter = customerGroup != null ?
                new ObjectParameter("customerGroup", customerGroup) :
                new ObjectParameter("customerGroup", typeof(string));
    
            var locationCodeParameter = locationCode != null ?
                new ObjectParameter("locationCode", locationCode) :
                new ObjectParameter("locationCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ItemsViewProcedure_Result>("ItemsViewProcedure", customerCodeParameter, customerGroupParameter, locationCodeParameter);
        }
    }
}
