//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSMessageEntry
    {
        public long Id { get; set; }
        public string EntryNo { get; set; }
        public string SenderID { get; set; }
        public string ReceiverID { get; set; }
        public string Text { get; set; }
        public System.DateTime SendDateTime { get; set; }
        public Nullable<System.DateTime> ReadDateTime { get; set; }
        public bool IsRead { get; set; }
        public string SenderSalespersCode { get; set; }
        public string ReceiverSalespersCode { get; set; }
        public Nullable<bool> ReadStatusChange { get; set; }
    }
}
