//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSubGroup
    {
        public string ProductSubGroup_Item_Category_Code { get; set; }
        public string ProductSubGroup_Product_Group_Code { get; set; }
        public string ProductSubGroup_Code { get; set; }
        public string ProductSubGroup_Description { get; set; }
    }
}
