//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectedItemReceipt
    {
        public string ItemNo_ { get; set; }
        public System.DateTime ReceiptDate { get; set; }
        public decimal Quantity { get; set; }
    }
}
