//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReleasedSalesLine
    {
        public string DocumentNo_ { get; set; }
        public int DocumentType { get; set; }
        public int LineNo_ { get; set; }
        public Nullable<int> Type { get; set; }
        public string No_ { get; set; }
        public string No2 { get; set; }
        public string Description { get; set; }
        public string LargeDescription { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public string Sell_toCustomerNo { get; set; }
        public string LocationCode { get; set; }
        public Nullable<decimal> Inv_DiscountAmount { get; set; }
        public Nullable<decimal> LineDiscountPercent { get; set; }
        public Nullable<decimal> LineDiscountAmount { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> AmountIncludingVAT { get; set; }
        public Nullable<decimal> GrossWeight { get; set; }
        public Nullable<decimal> NetWeight { get; set; }
        public Nullable<decimal> UnitVolume { get; set; }
        public string UnitOfMeasureCode { get; set; }
        public Nullable<decimal> QuantityBase { get; set; }
        public string ResponsibilityCenter { get; set; }
        public string ItemCategoryCode { get; set; }
        public string ProductGroupCode { get; set; }
        public string ProdSubGroupCode { get; set; }
        public Nullable<int> OrderType { get; set; }
        public string ModifiedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Shelf { get; set; }
        public string Service_Provider { get; set; }
        public string Service_Provider_Name { get; set; }
        public string Customer_Vehicle { get; set; }
    }
}
