//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salesperson_Purchaser
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> CommissionPercent { get; set; }
        public string PhoneNo_ { get; set; }
        public string JobTitle { get; set; }
        public string ResponsibilityCenter { get; set; }
        public string Type { get; set; }
        public Nullable<System.Guid> ModifiedUserID { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Auth_CardNo_ { get; set; }
        public byte[] MotivationPicture { get; set; }
    }
}
