//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesPrice
    {
        public string ItemNo_ { get; set; }
        public string SalesCode { get; set; }
        public string CurrencyCode { get; set; }
        public System.DateTime StartingDate { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<bool> PriceIncludingVAT { get; set; }
        public Nullable<bool> AllowInvoiceDisc { get; set; }
        public int SalesType { get; set; }
        public decimal MinimumQuantity { get; set; }
        public Nullable<System.DateTime> EndingDate { get; set; }
        public string UnitOfMeasureCode { get; set; }
        public string VariantCode { get; set; }
        public Nullable<bool> AllowLineDisc_ { get; set; }
        public Nullable<System.Guid> ModifiedUserID { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string VATBus_PostingGr__Price_ { get; set; }
    }
}
