//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public int Settings_No { get; set; }
        public string Settings_SalesPersonCode { get; set; }
        public string Settings_SalesPersonName { get; set; }
        public string Settings_ResponsibilityCenter { get; set; }
        public string Settings_Location { get; set; }
        public string Settings_SalesHeaderPrefix { get; set; }
        public string Settings_ReturnHeaderPrefix { get; set; }
        public string Settings_GenCustomerCode { get; set; }
        public string Settings_DiplomaticCustomerCode { get; set; }
        public string Settings_NavSQLServer { get; set; }
        public string Settings_NavSQLDatabase { get; set; }
        public string Settings_NavSQLUser { get; set; }
        public string Settings_NavSQLPass { get; set; }
        public string Settings_NavCompanyName { get; set; }
        public string Settings_DBVersion { get; set; }
        public string Settings_ManagerCode { get; set; }
        public string Settings_ManagerName { get; set; }
        public string Settings_ShopName { get; set; }
        public string Settings_ShopAddress { get; set; }
        public string Settings_ShopTel { get; set; }
        public string Settings_ShopWebAddress { get; set; }
        public string Settings_ShopReturnTerms { get; set; }
        public string Settings_ShopThanks { get; set; }
        public Nullable<bool> Settings_ShopPrintReceipt { get; set; }
        public string Settings_PosServiceUrl { get; set; }
        public string Settings_PosServiceUrl1 { get; set; }
        public string Settings_PosServiceUrl2 { get; set; }
        public string Settings_PosServiceUrl3 { get; set; }
        public string Settings_PosServiceUrl4 { get; set; }
        public string Settings_PosServiceUrl5 { get; set; }
        public string Settings_PosServiceUrl6 { get; set; }
        public string Settings_PosServiceUrl7 { get; set; }
        public string Settings_ResponsibilityCenterName { get; set; }
        public string Settings_QoutePrefix { get; set; }
        public string Settings_SpecOrderPrefix { get; set; }
        public string Settings_JnlTemplateName { get; set; }
        public string Settings_JnlBatchName { get; set; }
        public string Settings_RespEmployee { get; set; }
        public string Settings_PaymentOrderPrefix { get; set; }
        public string Settings_TransitLocation { get; set; }
        public string Settings_DomainName { get; set; }
        public string Settings_DomainUserName { get; set; }
        public string Settings_DomainPassword { get; set; }
        public string Settings_JnlGeneralBatchName { get; set; }
        public string Settings_ChangeSuggestionsInMinutes { get; set; }
        public string Settings_SalesHeaderNumberCount { get; set; }
        public string Settings_ConcurrentQoutePrefix { get; set; }
        public Nullable<int> Settings_Show_Shelf { get; set; }
        public string Settings_LocationAll { get; set; }
        public string Settings_RsUsername { get; set; }
        public string Settings_RsPassword { get; set; }
        public string Settings_RsServiceUsername { get; set; }
        public string Settings_RsServicePassword { get; set; }
    }
}
