//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ship_to_Address
    {
        public string CustomerNo_ { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Name_2 { get; set; }
        public string Address { get; set; }
        public string Address_2 { get; set; }
        public string City { get; set; }
        public string Contact { get; set; }
        public string PhoneNo_ { get; set; }
        public string ShippingAgentCode { get; set; }
        public string FullName { get; set; }
        public string Visit_Week_Days { get; set; }
        public string Shipping_Week_Days { get; set; }
        public string Shipment_Address_Code { get; set; }
    }
}
