//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSetup
    {
        public string UserID { get; set; }
        public string POSPass { get; set; }
        public string Salespers_Purch_Code { get; set; }
        public string Substitute { get; set; }
        public string SalesResp_Ctr_Filter { get; set; }
        public string PurchaseResp_Ctr_Filter { get; set; }
        public string ServiceResp_Ctr_Filter { get; set; }
        public Nullable<bool> AllowDiscount { get; set; }
        public Nullable<int> POSUserType { get; set; }
        public Nullable<System.Guid> ModifiedUserID { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
