//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public string Vehicle_No_ { get; set; }
        public string Model { get; set; }
        public string Owner_No_ { get; set; }
        public string Owner_Name { get; set; }
        public int Ownership { get; set; }
        public string Registration_No_ { get; set; }
        public string Trail_Registration_No_ { get; set; }
        public string Tranzit_Location_Code { get; set; }
        public int Type { get; set; }
        public string Driver_Code { get; set; }
        public string Driver_Name { get; set; }
        public string Driver_ID { get; set; }
        public string WIN_Code { get; set; }
    }
}
