//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleModel
    {
        public string ManufacturerCode { get; set; }
        public string ModelNo_ { get; set; }
        public string CabType { get; set; }
        public string Engine { get; set; }
        public string ManufacturerName { get; set; }
        public string ModelDescription { get; set; }
        public System.DateTime ManufacturingStartDate { get; set; }
        public Nullable<System.DateTime> ManufacturingEndDate { get; set; }
        public Nullable<int> DriveType { get; set; }
        public string Series { get; set; }
        public string Output_KW_ { get; set; }
        public string Output_PH_ { get; set; }
        public string Tech_EngineCapacity_CC_ { get; set; }
        public Nullable<int> Cylinder { get; set; }
        public Nullable<int> ValvesperCylinder { get; set; }
        public Nullable<int> EngineType { get; set; }
        public Nullable<int> Transmission { get; set; }
        public Nullable<int> FuelMixtureFormation { get; set; }
        public Nullable<int> BrakeSystem { get; set; }
        public Nullable<int> BrakeType { get; set; }
        public Nullable<int> ASR { get; set; }
        public Nullable<int> CatalyticConverterType { get; set; }
        public Nullable<int> AirCondition { get; set; }
        public Nullable<int> Drive { get; set; }
        public Nullable<decimal> Voltage { get; set; }
        public string Wheelbase { get; set; }
        public string TecDoc_ID { get; set; }
        public string Tonnage { get; set; }
        public string Axle { get; set; }
        public Nullable<int> Gas_norm { get; set; }
        public Nullable<int> ABS { get; set; }
        public string Axle_position { get; set; }
        public string Suspension { get; set; }
        public Nullable<int> Body_Model_Type { get; set; }
        public Nullable<int> Timings { get; set; }
    }
}
