//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor
    {
        public string No_ { get; set; }
        public string Name { get; set; }
        public string Country_Region_Code { get; set; }
        public string VAT_Registration_No_ { get; set; }
    }
}
